# Generated by Django 3.2.9 on 2021-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decs',
            new_name='desc',
        ),
    ]
